---
title: "Literature search document"
author: "Julian Flowers"
date: "09/01/2018"
output: html_document
runtime: shiny
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, cache = FALSE)
if(!require("myScraper"))
devtools::install_github("julianflowers/myScrapers")

library(myScrapers)
library(tidyverse)
library(DT)



```

A quick and dirty tool to search and extract Pubmed abstracts





```{r inputs, echo=FALSE, cache = FALSE}
inputPanel(
  textInput("search_text", label = "Enter search term", value = "machine learning population health", width = "400px"),
  
  numericInput("n", label = "No of abstracts",
              min = 100, max = 30000, value = 1000, step = 1000),
  
  numericInput("start_year", label = "Start year",
              min = 2000, max = 2018, value = 2010, step = 1)
  
)

```

## Search results

**Your query is `r renderText(EUtilsSummary(input$search_text)@querytranslation)`.**


**This returns `r renderText(EUtilsSummary(input$search_text)@count)` results.**

## Results table

```{r}




renderDataTable({
  
output <- pubmedAbstractR(input$search_text, n = input$n , start = input$start_year)
  
   output %>%
    mutate(link = paste0("https://www.ncbi.nlm.nih.gov/pubmed/",DOI), 
         url = paste0("<a href=", link, ">Link</a>") ) %>%
  select(-link) %>%
  DT::datatable(  escape = FALSE, filter = "top", extensions = 'Buttons', options = list(pageLength = 25,
    dom = 'Bfrtip',
    buttons = c('csv', 'excel', 'pdf')))
  

})

```

